### ISSUE TITLE
get rid of navbar

### ISSUE THREAD

**Issue by JeanHuit** [GDGGhana/devmap-firebase#1]
I cleaned out the navbar, however it seems there is some residual code, css or otherwise. 
Lets get rid of that.
Map should take up the entire screen.
@jeffgodwyll

**Comment by jeffgodwyll** [comment]
With the navbar still present? I think the search feature could seem useful later when we load locations from firebase.

Also there's currently a side menu? Should also go I guess.

**Comment by JeanHuit** [comment]
@jeffgodwyll  I think I did not explain the issue well, but I see you have done exactly that. Yup, I also thought so, for the search bar. My issue was with the sidebar only.

**Comment by jeffgodwyll** [comment]
Cool so closed?
