### ISSUE TITLE
Request permission to use geoLocation API, in different browsers.

### ISSUE THREAD

**Issue by JeanHuit** [GDGGhana/devmap-firebase#2]
This has different ,if very slight implementations in Chrome and Mozilla, however, the other browsers do not properly support this -> request permission.
What I have done with the geolocation branch is to fall back on a default location if there is an error getting a lock on location be it from permission denial or inability to request for permission. @jeffgodwyll have a look.

**Comment by jeffgodwyll** [comment]
> however, the other browsers do not properly support this -> request permission.

@JeanHuit 
I haven't reviewed the code, but I just opened the site in Chrome, Firefox and Safari. Chrome and Firefox got my location.(Share box popped up)

| |chrome|firefox|safari
|-|-------|-------|-----|
|**version** | 57.0.2950.4 dev (64-bit) | rv:50.0 | 9.1.2 (11601.7.7)|
|**request permission prompt**| yes | yes | yes |
|**gets location** | yes | yes | no(fall's back to default) |

I guess the work done is solid in this case.

**Comment by JeanHuit** [comment]
I also realised it. Later. They all  do request for the use of the location, except safari.
Cool
